
services:
  facultad-microservice:
    image: nicoledani/facultad-microservice:latest
    container_name: facultad-microservice
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8088:8088"
      - "8089:8089"
    environment:
      - DB_USER=userdb
      - DB_PASS=passdb
      - JPA_DDL=create-drop
      - DB_URL=jdbc:postgresql://db3:5433/curso_springboot
      - EUREKA_HOST=eurekaserver
      - EUREKA_PORT=8761
      - PORT=8088
      - ACTUATOR_PORT=8089
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
